# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
java_version=25
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
## Environment Properties
minecraft_version_range=[26.1,26.2)
neo_version_range=[21,)
loader_version_range=[4,)
interface_injection=false
## Mod Properties
mod_license=MIT
mod_version=2.0.0
mod_group_id=dev.anvilcraft.lib
mod_authors=Gugle
mod_description=Library mod developed by Anvil Dev
