pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

include 'renderdoc-loader'
include 'module.codec'
include 'module.collision'
include 'module.config'
include 'module.explosion'
include 'module.font'
include 'module.integration'
include 'module.moveable-entity-block'
include 'module.multiblock'
include 'module.network'
include 'module.recipe'
include 'module.registrum'
include 'module.rendering'
include 'module.rpc'
include 'module.space-select'
include 'module.sync'
include 'module.util'
include 'module.wheel'
include 'module.main'
include 'module.test'

project(':renderdoc-loader').name = 'renderdoc-loader-internal'
project(':module.codec').name = 'anvillib-codec-neoforge-26.1'
project(':module.collision').name = 'anvillib-collision-neoforge-26.1'
project(':module.config').name = 'anvillib-config-neoforge-26.1'
project(':module.explosion').name = 'anvillib-explosion-neoforge-26.1'
project(':module.font').name = 'anvillib-font-neoforge-26.1'
project(':module.integration').name = 'anvillib-integration-neoforge-26.1'
project(':module.moveable-entity-block').name = 'anvillib-moveable-entity-block-neoforge-26.1'
project(':module.multiblock').name = 'anvillib-multiblock-neoforge-26.1'
project(':module.network').name = 'anvillib-network-neoforge-26.1'
project(':module.recipe').name = 'anvillib-recipe-neoforge-26.1'
project(':module.registrum').name = 'anvillib-registrum-neoforge-26.1'
project(':module.rendering').name = 'anvillib-rendering-neoforge-26.1'
project(':module.rpc').name = 'anvillib-rpc-neoforge-26.1'
project(':module.space-select').name = 'anvillib-space-select-neoforge-26.1'
project(':module.sync').name = 'anvillib-sync-neoforge-26.1'
project(':module.util').name = 'anvillib-util-neoforge-26.1'
project(':module.wheel').name = 'anvillib-wheel-neoforge-26.1'
project(':module.main').name = 'anvillib-neoforge-26.1'
project(':module.test').name = 'anvillib-test-neoforge-26.1'
