[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.76"
modDevGradle = "2.0.141"
lombok = "9.2.0"
machete = "2.0.1"

[libraries]
neoForge = { group = "net.neoforged", name = "neoforge", version.ref = "neoForge" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
