dependencies {
    if (System.getenv("NOT_DEV") == 'true') {
        jarJar(api("dev.anvilcraft.lib:anvillib-sync-processor-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-codec-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-network-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-util-neoforge-1.21.11:latest.release"))
    } else {
        jarJar(api project(":anvillib-sync-neoforge-1.21.11:anvillib-sync-processor-neoforge-1.21.11"))
        jarJar(api project(":anvillib-codec-neoforge-1.21.11"))
        jarJar(api project(":anvillib-network-neoforge-1.21.11"))
        jarJar(api project(":anvillib-util-neoforge-1.21.11"))
    }
}
