dependencies {
    if (System.getenv("NOT_DEV") == 'true') {
        jarJar(api("dev.anvilcraft.lib:anvillib-config-neoforge-26.1:latest.release"))
    } else {
        jarJar(implementation project(":anvillib-config-neoforge-26.1"))
    }
    jarJar(implementation("at.yawk.lz4:lz4-java:1.10.1"))
    jarJar(implementation("com.github.luben:zstd-jni:1.5.7-7"))
}
