dependencies {
    implementation project(":anvillib-codec-neoforge-26.1")
    implementation project(":anvillib-config-neoforge-26.1")
    implementation project(":anvillib-font-neoforge-26.1")
    interfaceInjectionData(implementation project(":anvillib-font-neoforge-26.1"))
    implementation project(":anvillib-integration-neoforge-26.1")
    interfaceInjectionData(implementation project(":anvillib-moveable-entity-block-neoforge-26.1"))
    implementation project(":anvillib-multiblock-neoforge-26.1")
    implementation project(":anvillib-network-neoforge-26.1")
    interfaceInjectionData(implementation project(":anvillib-recipe-neoforge-26.1"))
    implementation project(":anvillib-registrum-neoforge-26.1")
    implementation project(":anvillib-rendering-neoforge-26.1")
    implementation project(":anvillib-space-select-neoforge-26.1")
    implementation project(":anvillib-sync-neoforge-26.1")
    implementation project(":anvillib-util-neoforge-26.1")
    implementation project(":anvillib-wheel-neoforge-26.1")
}
