plugins {
    id 'java'
    id 'maven-publish'
    alias libs.plugins.lombok
    alias libs.plugins.jreleaser
}

String buildType = 'snapshot'
String buildNumber
if (System.getenv("CI_BUILD") == 'false') buildNumber = null else {
    if (System.getenv("PR_BUILD") != 'false') buildType = 'pr'
    buildNumber = System.getenv("GITHUB_RUN_NUMBER")
}
version = "${mod_version}" + (buildNumber != null ? "+${buildType}.${buildNumber}" : "")
group = mod_group_id

base {
    archivesName = "${project.mod_id}-neoforge-${libs.versions.minecraft.get()}"
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.2-1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    manifest {
        attributes(
            'Premain-Class': 'dev.anvilcraft.lib.renderdoc.loader.RenderDocAgent',
            'Agent-Class': 'dev.anvilcraft.lib.renderdoc.loader.RenderDocAgent',
            'Can-Redefine-Classes': 'false',
            'Can-Retransform-Classes': 'false',
            'Can-Set-Native-Method-Prefix': 'false'
        )
    }
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allSource
    archiveClassifier = 'sources'
}

tasks.register('javadocJar', Jar) {
    from javadoc.destinationDir
    dependsOn javadoc
    archiveClassifier = 'javadoc'
}

javadoc {
    // options.encoding = 'UTF-8'
    options {
        encoding = 'UTF-8'
        addStringOption 'Xdoclint:none', '-quiet'
        addStringOption 'tag', 'apiNote:a:API Note:'
        addStringOption 'tag', 'implSpec:a:Implementation Requirement:'
        addStringOption 'tag', 'implNote:a:Implementation Note:'
    }
}

artifacts {
    archives tasks.jar
    archives tasks.sourcesJar
    archives tasks.javadocJar
}

def this_name = base.archivesName.get()
def this_description = mod_description

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java

            artifact sourcesJar
            artifact javadocJar

            pom {
                name = this_name
                description = this_description
                url = 'https://github.com/Anvil-Dev/AnvilLib'

                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/license/mit'
                    }
                }
                developers {
                    developer {
                        id = 'Anvil-Dev'
                        name = 'AnvilCraft Dev'
                        email = 'admin@anvilcraft.dev'
                    }
                }
                scm {
                    url = 'https://github.com/Anvil-Dev/AnvilLib'
                    connection = 'https://github.com/Anvil-Dev/AnvilLib.git'
                    developerConnection = 'https://github.com/Anvil-Dev/AnvilLib.git'
                }
            }
        }
    }
    repositories {
        mavenLocal()
    }
}

jreleaser {
    signing {
        active = 'ALWAYS'
        armored = true
    }

    deploy {
        maven {
            mavenCentral {
                sonatype {
                    active = 'ALWAYS'
                    url = 'https://central.sonatype.com/api/v1/publisher'
                    stagingRepository('build/staging-deploy')
                }
            }
        }
    }
}

lombok {
    version = "1.18.44"
}
