dependencies {
    if (System.getenv("NOT_DEV") == 'true') {
        jarJar(api("dev.anvilcraft.lib:anvillib-codec-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-cube-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-collision-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-config-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-explosion-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-font-neoforge-1.21.11:latest.release"))
        interfaceInjectionData("dev.anvilcraft.lib:anvillib-font-neoforge-1.21.11:latest.release")
        jarJar(api("dev.anvilcraft.lib:anvillib-integration-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-moveable-entity-block-neoforge-1.21.11:latest.release"))
        interfaceInjectionData("dev.anvilcraft.lib:anvillib-moveable-entity-block-neoforge-1.21.11:latest.release")
        jarJar(api("dev.anvilcraft.lib:anvillib-multiblock-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-network-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-recipe-neoforge-1.21.11:latest.release"))
        interfaceInjectionData("dev.anvilcraft.lib:anvillib-recipe-neoforge-1.21.11:latest.release")
        jarJar(api("dev.anvilcraft.lib:anvillib-registrum-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-rendering-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-rpc-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-space-select-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-sync-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-util-neoforge-1.21.11:latest.release"))
        jarJar(api("dev.anvilcraft.lib:anvillib-wheel-neoforge-1.21.11:latest.release"))
    } else {
        jarJar(api project(":anvillib-codec-neoforge-1.21.11"))
        jarJar(api project(":anvillib-cube-neoforge-1.21.11"))
        jarJar(api project(":anvillib-collision-neoforge-1.21.11"))
        jarJar(api project(":anvillib-config-neoforge-1.21.11"))
        jarJar(api project(":anvillib-explosion-neoforge-1.21.11"))
        jarJar(api project(":anvillib-font-neoforge-1.21.11"))
        interfaceInjectionData project(":anvillib-font-neoforge-1.21.11")
        jarJar(api project(":anvillib-integration-neoforge-1.21.11"))
        jarJar(api project(":anvillib-moveable-entity-block-neoforge-1.21.11"))
        interfaceInjectionData project(":anvillib-moveable-entity-block-neoforge-1.21.11")
        jarJar(api project(":anvillib-multiblock-neoforge-1.21.11"))
        jarJar(api project(":anvillib-network-neoforge-1.21.11"))
        jarJar(api project(":anvillib-recipe-neoforge-1.21.11"))
        interfaceInjectionData project(":anvillib-recipe-neoforge-1.21.11")
        jarJar(api project(":anvillib-registrum-neoforge-1.21.11"))
        jarJar(api project(":anvillib-rendering-neoforge-1.21.11"))
        jarJar(api project(":anvillib-rpc-neoforge-1.21.11"))
        jarJar(api project(":anvillib-space-select-neoforge-1.21.11"))
        jarJar(api project(":anvillib-sync-neoforge-1.21.11"))
        jarJar(api project(":anvillib-util-neoforge-1.21.11"))
        jarJar(api project(":anvillib-wheel-neoforge-1.21.11"))
    }
}

publishMods {
    file = jar.archiveFile
    changelog = "Update"
    type = BETA
    modLoaders.add("neoforge")

    additionalFiles.from(sourcesJar.archiveFile)
    additionalFiles.from(javadocJar.archiveFile)

    curseforge {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        projectId = "1484302"
        clientRequired = true
        serverRequired = true
        minecraftVersions.add(libs.versions.minecraft.get())
    }

    modrinth {
        accessToken = System.getenv("MODRINTH_TOKEN")
        projectId = "nKAcAL9b"
        minecraftVersions.add(libs.versions.minecraft.get())
    }
}
