name: CI for Mod
on:
  workflow_dispatch:
  push:
    branches:
      - dev/**
      # - releases/**
    paths:
      - module.*/src/**
      - module.*/build.gradle
      - module.*/gradle.properties
      - build.gradle
      - gradle.properties
      - settings.gradle

jobs:
  codec:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: codec
      module_id: anvillib-codec
      mod_id: anvillib_codec
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  codec-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - codec
    with:
      module: codec
      module_id: anvillib-codec
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  config:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: config
      module_id: anvillib-config
      mod_id: anvillib_config
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  config-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - config
    with:
      module: config
      module_id: anvillib-config
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  font:
    needs:
      - rendering
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: font
      module_id: anvillib-font
      mod_id: anvillib_font
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  font-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - font
    with:
      module: font
      module_id: anvillib-font
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  integration:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: integration
      module_id: anvillib-integration
      mod_id: anvillib_integration
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  integration-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - integration
    with:
      module: integration
      module_id: anvillib-integration
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  moveable-entity-block:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: moveable-entity-block
      module_id: anvillib-moveable-entity-block
      mod_id: anvillib_moveable_entity_block
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  moveable-entity-block-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - moveable-entity-block
    with:
      module: moveable-entity-block
      module_id: anvillib-moveable-entity-block
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  multiblock:
    uses: ./.github/workflows/build_and_test.yml
    needs:
      - codec
      - config
      - network
      - util
    with:
      module: multiblock
      module_id: anvillib-multiblock
      mod_id: anvillib_multiblock
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  multiblock-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - multiblock
    with:
      module: multiblock
      module_id: anvillib-multiblock
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  network:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: network
      module_id: anvillib-network
      mod_id: anvillib_network
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  network-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - network
    with:
      module: network
      module_id: anvillib-network
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  recipe:
    needs:
      - codec
      - config
      - util
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: recipe
      module_id: anvillib-recipe
      mod_id: anvillib_recipe
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  recipe-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - recipe
    with:
      module: recipe
      module_id: anvillib-recipe
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  registrum:
    uses: ./.github/workflows/build_and_test.yml
    needs:
      - util
    with:
      module: registrum
      module_id: anvillib-registrum
      mod_id: anvillib_registrum
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  registrum-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - registrum
    with:
      module: registrum
      module_id: anvillib-registrum
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  rendering:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: rendering
      module_id: anvillib-rendering
      mod_id: anvillib_rendering
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  rendering-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - rendering
    with:
      module: rendering
      module_id: anvillib-rendering
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  space-select:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: space-select
      module_id: anvillib-space-select
      mod_id: anvillib_space_select
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  space-select-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - space-select
    with:
      module: space-select
      module_id: anvillib-space-select
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  sync:
    uses: ./.github/workflows/build_and_test.yml
    needs:
      - codec
      - network
      - util
    with:
      module: sync
      module_id: anvillib-sync
      mod_id: anvillib_sync
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  sync-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - sync
    with:
      module: sync
      module_id: anvillib-sync
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  util:
    uses: ./.github/workflows/build_and_test.yml
    needs:
      - codec
    with:
      module: util
      module_id: anvillib-util
      mod_id: anvillib_util
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  util-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - util
    with:
      module: util
      module_id: anvillib-util
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  wheel:
    uses: ./.github/workflows/build_and_test.yml
    needs:
      - rendering
      - util
    with:
      module: wheel
      module_id: anvillib-wheel
      mod_id: anvillib_wheel
      ci_build: true
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
  wheel-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - wheel
    with:
      module: wheel
      module_id: anvillib-wheel
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
  main:
    needs:
      - codec
      - config
      - font
      - integration
      - moveable-entity-block
      - multiblock
      - network
      - recipe
      - registrum
      - rendering
      - space-select
      - sync
      - util
      - wheel
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: main
      module_id: anvillib
      mod_id: anvillib
      ci_build: true
      pr_build: false
      gametest: true
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}
      curseforge_token: ${{ secrets.CURSEFORGE_TOKEN }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
  main-maven-central-deploy:
    uses: ./.github/workflows/publish_maven_central.yml
    needs:
      - main
    with:
      module: main
      module_id: anvillib
    secrets:
      maven_central_username: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      maven_central_password: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      signing_key: ${{ secrets.SIGNING_KEY }}
      signing_public_key: ${{ secrets.SIGNING_PUBLIC_KEY }}
      signing_password: ${{ secrets.SIGNING_PASSWORD }}
